---
# tasks file for apache_deploy

- name: Install Apache on Ubuntu
  apt:
    name: apache2
    state: present
  become: true

- name: Copy index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: Ensure Apache service is running
  service:
    name: apache2
    state: restarted
  become: true
